server:
  port: 8080

spring:
  application:
    name: USER_APPLICATION
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/user
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
